# Generated by Django 4.2.5 on 2023-09-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('content', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
