# Generated by Django 4.2.5 on 2023-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/static/imeges/no_image.png', upload_to='media/'),
        ),
    ]
