# Generated by Django 4.2.5 on 2023-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/static/images/no_image.png', upload_to='media/'),
        ),
    ]
