# Generated by Django 4.2.5 on 2023-09-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slugify_name',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=100),
        ),
    ]
