# Generated by Django 4.2.5 on 2023-09-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_slugify_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slugify_name',
        ),
    ]
