# Generated by Django 4.2.5 on 2023-09-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
